force-app/main/default/objects/KTA_Job__c/KTA_Job__c.object-meta.xml
<CustomObject>
    <label>KTA Job</label>
    <nameField>
        <label>KTA Job</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KTA Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ta-connector/main/default/objects/KTA_Job__c/fields/Inbound_Request_Flow_Inputs__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Request_Flow_Inputs__c</fullName>
    <label>Inbound Request Flow Inputs</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ta-connector/main/default/objects/KTA_Job__c/fields/Inbound_Request_JSON__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Request_JSON__c</fullName>
    <label>Inbound Request JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/KTA_Job__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Total_Agility_Process_Configurations__mdt/Total_Agility_Process_Configurations__mdt.object-meta.xml
<CustomObject>
    <label>Total Agility Process Configurations</label>
    <pluralLabel>Total Agility Process Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/TotalAgility_System_Configurations__c/TotalAgility_System_Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TotalAgility System Configurations</label>
</CustomObject>

ta-connector/main/default/objects/TotalAgility_System_Configurations__c/fields/Log_Cleanup_Cutoff_Days__c.field-meta.xml
<CustomField>
    <fullName>Log_Cleanup_Cutoff_Days__c</fullName>
    <label>Job Log Clean up Cutoff Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ta-connector/main/default/objects/TotalAgility_System_Configurations__c/fields/Log_Job_inbound_and_outbound_Requests__c.field-meta.xml
<CustomField>
    <fullName>Log_Job_inbound_and_outbound_Requests__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Log Job inbound and outbound  Requests</label>
    <type>Checkbox</type>
</CustomField>

ta-connector/main/default/objects/TotalAgility_System_Configurations__c/fields/Session_ID__c.field-meta.xml
<CustomField>
    <fullName>Session_ID__c</fullName>
    <label>Session ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ta-connector/main/default/objects/TotalAgility_System_Configurations__c/fields/Total_Agility_End_point_URL__c.field-meta.xml
<CustomField>
    <fullName>Total_Agility_End_point_URL__c</fullName>
    <label>Total Agility End point URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TAJobResponseTriggerTest.cls
/**
 * @description       :
 * @author            : Unni
 * @group             :
 * @last modified on  : 01-18-2025
 * @last modified by  : Unni
 **/
@IsTest
private class TAJobResponseTriggerTest {
    
    @testSetup
    static void setup() {
        // Create an org-level instance of the custom setting
        TotalAgility_System_Configurations__c orgLevelSetting =
            new TotalAgility_System_Configurations__c(
            // Set field values
        Log_Cleanup_Cutoff_Days__c = 30,
        Log_Job_inbound_and_outbound_Requests__c = true,
        Session_ID__c = 'TestSession12345',
        Total_Agility_End_point_URL__c = 'https://example.com/endpoint'
            );
        
        // Insert the custom setting
        insert orgLevelSetting;
    }
    
    @IsTest
    static void testJobresponseApexExecution() {
        List<Total_Agility_Process_Configurations__mdt> processConfigurations = (List<Total_Agility_Process_Configurations__mdt>)Json.deserialize('[{"tungstenconnect__Callback_Execution_Method__c":"Apex","tungstenconnect__Callback_Logi_Apex_or_Flow_name__c":"TAJobResponseTriggerTest.TACallbackProcessorTest","tungstenconnect__Flow_Variable_mapping__c":"","tungstenconnect__Total_Agility_Process_Name__c":"accountCreationProcess"}]', List<Total_Agility_Process_Configurations__mdt>.class);
        Test.startTest();
        String responseMessage = '{"Name": "Acme Corporation", "Phone": "123-456-7890", "Industry": "Technology"}';
        TAJobResponseHelper.processConfigurations = processConfigurations;

        tungstenconnect__JobResponse__e jobEvent = new tungstenconnect__JobResponse__e(
            tungstenconnect__Process_Name__c = 'accountCreationProcess',
            tungstenconnect__Response_Message__c = responseMessage,
            tungstenconnect__Response_Timestamp__c = DateTime.now()
        );

        // Publish the platform event
        Database.SaveResult publishResult = EventBus.publish(jobEvent);

        // Assert that the platform event was published successfully
        System.assert(publishResult.isSuccess(), 'Platform event was not published successfully');

        // Deliver the event to trigger subscribers
        Test.getEventBus().deliver();

        Test.stopTest();

        Account account = [SELECT Id, Name, Phone, Industry FROM Account LIMIT 1];
        System.Assert.areEqual('Acme Corporation', account.Name, 'Account not created');
        
    }
    
    public Class TACallbackProcessorTest implements TACallbackProcessor {
        public void execute(String message) {
            System.debug('message received: ' + message);
            // Implement the logic for the execute method
            Account account = (Account)Json.deserialize(message, Account.class);
            insert account;
        }
        
    }

    @IsTest
    static void testJobresponseFlowExecution() {
        List<Total_Agility_Process_Configurations__mdt> processConfigurations = (List<Total_Agility_Process_Configurations__mdt>)Json.deserialize('[{"tungstenconnect__Callback_Execution_Method__c":"Flow","tungstenconnect__Callback_Logi_Apex_or_Flow_name__c":"testFlow","tungstenconnect__Flow_Variable_mapping__c":"{\\\"Name\\\":\\\"Name\\\",\\\"Phone\\\":\\\"Phone\\\"}","tungstenconnect__Total_Agility_Process_Name__c":"accountCreationProcess"}]', List<Total_Agility_Process_Configurations__mdt>.class);
        Test.startTest();
        String responseMessage = '{"Name": "Acme Corporation", "Phone": "123-456-7890", "Industry": "Technology"}';
        TAJobResponseHelper.processConfigurations = processConfigurations;

        tungstenconnect__JobResponse__e jobEvent = new tungstenconnect__JobResponse__e(
            tungstenconnect__Process_Name__c = 'accountCreationProcess',
            tungstenconnect__Response_Message__c = responseMessage,
            tungstenconnect__Response_Timestamp__c = DateTime.now()
        );

        // Publish the platform event
        Database.SaveResult publishResult = EventBus.publish(jobEvent);

        // Assert that the platform event was published successfully
        System.assert(publishResult.isSuccess(), 'Platform event was not published successfully');

        // Deliver the event to trigger subscribers
        Test.getEventBus().deliver();

        Test.stopTest();
        KTA_Job__c job = [SELECT Id, Name, Inbound_Request_JSON__c, Inbound_Request_Flow_Inputs__c, Process_Name__c FROM KTA_Job__c LIMIT 1];
        System.Assert.areEqual('accountCreationProcess', job.Process_Name__c, 'Process name not matching');
        Map<String, Object> flowInputs = (Map<String, Object>)Json.deserializeUntyped(job.Inbound_Request_Flow_Inputs__c);
        System.Assert.areEqual('Acme Corporation', flowInputs.get('Name'), 'Name not matching');
        System.Assert.areEqual('123-456-7890', flowInputs.get('Phone'), 'Phone not matching');
        
    }

    @IsTest
    static void testFlowUtilityComplexFlowMapping() {
        List<Total_Agility_Process_Configurations__mdt> processConfigurations = (List<Total_Agility_Process_Configurations__mdt>)Json.deserialize('[{\"tungstenconnect__Callback_Execution_Method__c\":\"Flow\",\"tungstenconnect__Callback_Logi_Apex_or_Flow_name__c\":\"testFlow\",\"tungstenconnect__Flow_Variable_mapping__c\":\"{\\\"EmployeeAccount\\\":{\\\"Path\\\":\\\"EmployeeAccount\\\",\\\"SObject\\\":\\\"Account\\\",\\\"isCollection\\\":false,\\\"FieldsMapping\\\":{\\\"Name\\\":\\\"Name\\\",\\\"Phone\\\":\\\"Phone\\\"}}}\",\"tungstenconnect__Total_Agility_Process_Name__c\":\"accountCreationProcess\"}]', List<Total_Agility_Process_Configurations__mdt>.class);
        Test.startTest();
        String responseMessage = '{"EmployeeAccount":{"Name": "Acme Corporation", "Phone": "123-456-7890", "Industry": "Technology"}}';
        TAJobResponseHelper.processConfigurations = processConfigurations;

        tungstenconnect__JobResponse__e jobEvent = new tungstenconnect__JobResponse__e(
            tungstenconnect__Process_Name__c = 'accountCreationProcess',
            tungstenconnect__Response_Message__c = responseMessage,
            tungstenconnect__Response_Timestamp__c = DateTime.now()
        );

        // Publish the platform event
        Database.SaveResult publishResult = EventBus.publish(jobEvent);

        // Assert that the platform event was published successfully
        System.assert(publishResult.isSuccess(), 'Platform event was not published successfully');

        // Deliver the event to trigger subscribers
        Test.getEventBus().deliver();

        Test.stopTest();
        KTA_Job__c job = [SELECT Id, Name, Inbound_Request_JSON__c, Inbound_Request_Flow_Inputs__c, Process_Name__c FROM KTA_Job__c LIMIT 1];
        System.Assert.areEqual('accountCreationProcess', job.Process_Name__c, 'Process name not matching');
        Map<String, Object> flowInputs = (Map<String, Object>)Json.deserializeUntyped(job.Inbound_Request_Flow_Inputs__c);
        Map<String, Object> employeeAccountMap = (Map<String, Object>)flowInputs.get('EmployeeAccount');
        String employeeAccountJson = JSON.serialize(employeeAccountMap);
        Account acc = (Account)JSON.deserialize(employeeAccountJson, Account.class);
        System.Assert.areEqual('Acme Corporation', acc.Name, 'Name not matching');
        System.Assert.areEqual('123-456-7890', acc.Phone, 'Phone not matching');
        
    }

    @IsTest
    static void testFlowUtilityComplexFlowMappingCollection() {
        List<Total_Agility_Process_Configurations__mdt> processConfigurations = (List<Total_Agility_Process_Configurations__mdt>)Json.deserialize('[{\"tungstenconnect__Callback_Execution_Method__c\":\"Flow\",\"tungstenconnect__Callback_Logi_Apex_or_Flow_name__c\":\"testFlow\",\"tungstenconnect__Flow_Variable_mapping__c\":\"{\\\"EmployeeAccounts\\\":{\\\"Path\\\":\\\"EmployeeAccounts\\\",\\\"SObject\\\":\\\"Account\\\",\\\"isCollection\\\":true,\\\"FieldsMapping\\\":{\\\"Name\\\":\\\"Name\\\",\\\"Phone\\\":\\\"Phone\\\"}}}\",\"tungstenconnect__Total_Agility_Process_Name__c\":\"accountCreationProcess\"}]', List<Total_Agility_Process_Configurations__mdt>.class);
        Test.startTest();
        String responseMessage = '{"EmployeeAccounts":[{"Name": "Acme Corporation", "Phone": "123-456-7890", "Industry": "Technology"},{"Name": "Beta Corporation", "Phone": "778-456-4567", "Industry": "Technology"}]}';
        TAJobResponseHelper.processConfigurations = processConfigurations;

        tungstenconnect__JobResponse__e jobEvent = new tungstenconnect__JobResponse__e(
            tungstenconnect__Process_Name__c = 'accountCreationProcess',
            tungstenconnect__Response_Message__c = responseMessage,
            tungstenconnect__Response_Timestamp__c = DateTime.now()
        );

        // Publish the platform event
        Database.SaveResult publishResult = EventBus.publish(jobEvent);

        // Assert that the platform event was published successfully
        System.assert(publishResult.isSuccess(), 'Platform event was not published successfully');

        // Deliver the event to trigger subscribers
        Test.getEventBus().deliver();

        Test.stopTest();
        KTA_Job__c job = [SELECT Id, Name, Inbound_Request_JSON__c, Inbound_Request_Flow_Inputs__c, Process_Name__c FROM KTA_Job__c LIMIT 1];
        System.Assert.areEqual('accountCreationProcess', job.Process_Name__c, 'Process name not matching');
        Map<String, Object> flowInputs = (Map<String, Object>)Json.deserializeUntyped(job.Inbound_Request_Flow_Inputs__c);
        List<Object> employeeAccountList = (List<Object>)flowInputs.get('EmployeeAccounts');
        System.Assert.areEqual(2, employeeAccountList.size(), 'Accounts not matching');
    }
}