force-app/main/default/objects/KTA_Risk_Score_Setting__mdt/KTA_Risk_Score_Setting__mdt.object-meta.xml
<CustomObject>
    <label>KTA Risk Score Setting</label>
    <pluralLabel>KTA Risk Score Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/KTA_Risk_Score_Setting__mdt/fields/KTA_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>KTA_Endpoint__c</fullName>
    <description>Endpoint used by the KTA Risk Score Application</description>
    <label>KTA Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KTA_Risk_Score_Setting__mdt/fields/KTA_Process_Id__c.field-meta.xml
<CustomField>
    <fullName>KTA_Process_Id__c</fullName>
    <description>Process Id used by the KTA Risk Score Application</description>
    <label>KTA Process Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KTA_Risk_Score_Setting__mdt/fields/KTA_Session_Id__c.field-meta.xml
<CustomField>
    <fullName>KTA_Session_Id__c</fullName>
    <description>Session Id used by the KTA Risk Score Application</description>
    <label>KTA Session Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KTA_Risk_Score_Setting__mdt/fields/KTA_Task_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>KTA_Task_Record_Type__c</fullName>
    <description>Label of the Task Record Type used by the KTA Risk Score Application</description>
    <label>KTA Task Record Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KofaxKTAScore_Constants.cls
/**
* @apexClassName      : KofaxKTAScore_Constants
* @date               : August 7, 2023
* @description:       : Class with Constants for the KTA Risk Score application
*                       retrieved from Custom Metadata Type 
* @author             : John Hogan, johnejhogan@gmail.com
 */
public class KofaxKTAScore_Constants {
    public static KTA_Risk_Score_Setting__mdt SETTINGS = [SELECT Id, DeveloperName, KTA_Endpoint__c, KTA_Process_Id__c, KTA_Session_Id__c, KTA_Task_Record_Type__c FROM KTA_Risk_Score_Setting__mdt WHERE Active__c = true LIMIT 1];
    public static String KOFAX_RISK_REQUEST_VERSION = SETTINGS.DeveloperName;
    public static String KOFAX_ENDPOINT = SETTINGS.KTA_Endpoint__c;
    public static String KOFAX_PROCESS_ID = SETTINGS.KTA_Process_Id__c;
    public static String KOFAX_SESSION_ID = SETTINGS.KTA_Session_Id__c;
    public static String KOFAX_RISK_TASK_RECORD_TYPE = SETTINGS.KTA_Task_Record_Type__c;
    // public static String SFDC_ORG_KEY = SETTINGS.SFDC_OrgKey__c;

    // // 2023-11-29: added Lease settings
    // public static KTA_Lease_Setting__mdt SETTINGS_LEASE = [SELECT Id, DeveloperName, KTA_Endpoint__c, KTA_Process_Id__c, KTA_Session_Id__c, SFDC_OrgKey__c FROM KTA_Lease_Setting__mdt WHERE Active__c = true LIMIT 1];
    // public static String KOFAX_RISK_REQUEST_VERSION_LEASE = SETTINGS_LEASE.DeveloperName;
    // public static String KOFAX_ENDPOINT_LEASE = SETTINGS_LEASE.KTA_Endpoint__c;
    // public static String KOFAX_PROCESS_ID_LEASE = SETTINGS_LEASE.KTA_Process_Id__c;
    // public static String KOFAX_SESSION_ID_LEASE = SETTINGS_LEASE.KTA_Session_Id__c;
    // public static String SFDC_ORG_KEY_LEASE = SETTINGS_LEASE.SFDC_OrgKey__c;

    // // 2023-12-07: added Agreement settings
    // public static KTA_Agreement_Setting__mdt SETTINGS_AGREEMENT = [SELECT Id, DeveloperName, KTA_Endpoint__c, KTA_Process_Id__c, KTA_Session_Id__c, SFDC_OrgKey__c FROM KTA_Agreement_Setting__mdt WHERE Active__c = true LIMIT 1];
    // public static String KOFAX_RISK_REQUEST_VERSION_AGREEMENT = SETTINGS_AGREEMENT.DeveloperName;
    // public static String KOFAX_ENDPOINT_AGREEMENT = SETTINGS_AGREEMENT.KTA_Endpoint__c;
    // public static String KOFAX_PROCESS_ID_AGREEMENT = SETTINGS_AGREEMENT.KTA_Process_Id__c;
    // public static String KOFAX_SESSION_ID_AGREEMENT = SETTINGS_AGREEMENT.KTA_Session_Id__c;
    // public static String SFDC_ORG_KEY_AGREEMENT = SETTINGS_AGREEMENT.SFDC_OrgKey__c;
}