ta-connector/main/default/objects/JobResponse__e/JobResponse__e.object-meta.xml
<CustomObject>
    <description>Platform Event which publishes the Job response from TotalAgility.</description>
    <label>JobResponse</label>
    <pluralLabel>JobResponses</pluralLabel>
</CustomObject>

ta-connector/main/default/objects/JobResponse__e/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>Process which initiated the request</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ta-connector/main/default/objects/JobResponse__e/fields/Response_Message__c.field-meta.xml
<CustomField>
    <fullName>Response_Message__c</fullName>
    <description>Response message</description>
    <label>Response Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ta-connector/main/default/objects/KTA_Job__c/KTA_Job__c.object-meta.xml
<CustomObject>
    <label>KTA Job</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>KTA Job</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KTA Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ta-connector/main/default/objects/KTA_Job__c/fields/Exception__c.field-meta.xml
<CustomField>
    <fullName>Exception__c</fullName>
    <label>Exception</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ta-connector/main/default/objects/KTA_Job__c/fields/Inbound_Request_Flow_Inputs__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Request_Flow_Inputs__c</fullName>
    <label>Inbound Request Flow Inputs</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ta-connector/main/default/objects/KTA_Job__c/fields/Inbound_Request_JSON__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Request_JSON__c</fullName>
    <label>Inbound Request JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/KTA_Job__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ta-connector/main/default/objects/KTA_Job__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ta-connector/main/default/objects/Total_Agility_Process_Configurations__mdt/Total_Agility_Process_Configurations__mdt.object-meta.xml
<CustomObject>
    <label>TotalAgility Process Configurations</label>
    <pluralLabel>TotalAgility Process Configurations</pluralLabel>
</CustomObject>

ta-connector/main/default/objects/Total_Agility_Process_Configurations__mdt/fields/Callback_Execution_Method__c.field-meta.xml
<CustomField>
    <fullName>Callback_Execution_Method__c</fullName>
    <description>Select the method where the Process response callback logic is written or configured</description>
    <label>Callback Execution Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
                <default>true</default>
                <label>Apex</label>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ta-connector/main/default/objects/Total_Agility_Process_Configurations__mdt/fields/Callback_Logi_Apex_or_Flow_name__c.field-meta.xml
<CustomField>
    <fullName>Callback_Logi_Apex_or_Flow_name__c</fullName>
    <description>Call back Apex or FLow name which is going to process the response received from TotalAgility.</description>
    <label>Callback Logic Apex or Flow name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ta-connector/main/default/objects/Total_Agility_Process_Configurations__mdt/fields/Callback_Logic_Namespace__c.field-meta.xml
<CustomField>
    <fullName>Callback_Logic_Namespace__c</fullName>
    <description>Namespace for Callback logic.</description>
    <label>Callback Logic Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Total_Agility_Process_Configurations__mdt/fields/Flow_Variable_mapping__c.field-meta.xml
<CustomField>
    <fullName>Flow_Variable_mapping__c</fullName>
    <label>Flow Variable mapping</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ta-connector/main/default/objects/Total_Agility_Process_Configurations__mdt/fields/Total_Agility_Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Total_Agility_Process_Name__c</fullName>
    <description>The Process to be invoked in TotalAgility</description>
    <label>TotalAgility Process Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TotalAgility_System_Configurations__c/TotalAgility_System_Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TotalAgility System Configurations</label>
</CustomObject>

ta-connector/main/default/objects/TotalAgility_System_Configurations__c/fields/Log_Job_inbound_and_outbound_Requests__c.field-meta.xml
<CustomField>
    <fullName>Log_Job_inbound_and_outbound_Requests__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Log Job inbound and outbound  Requests</label>
    <type>Checkbox</type>
</CustomField>

ta-connector/main/default/classes/TAJobResponseHelper.cls
/**
 * @description       :
 * @author            : Unni
 * @group             :
 * @last modified on  : 02-18-2025
 * @last modified by  : Unni
 **/
public without sharing class TAJobResponseHelper {
    @testVisible static List<Total_Agility_Process_Configurations__mdt> processConfigurations{
        get{
            if(processConfigurations == NULL){
                processConfigurations = [SELECT Callback_Execution_Method__c,
            Callback_Logi_Apex_or_Flow_name__c,
            Callback_Logic_Namespace__c,
            Total_Agility_Process_Name__c,
            Flow_Variable_mapping__c
     FROM Total_Agility_Process_Configurations__mdt 
     WITH SYSTEM_MODE];
            }
            return processConfigurations;
        }
        set;
    }
    
    public static void processJobResponse(List<JobResponse__e> responses){
        // Collect all process names from the events
        Set<String> processNames = new Set<String>();
        for (JobResponse__e event : responses) {
            processNames.add(event.Process_Name__c);
            
        }
        System.debug('processNames'+ processNames );
        // Check if logging is enabled in custom settings
        TotalAgility_System_Configurations__c systemConfig = TotalAgility_System_Configurations__c.getInstance();
        Boolean isLoggingEnabled = (systemConfig != null) && systemConfig.Log_Job_inbound_and_outbound_Requests__c;
        
        // Query the custom metadata records based on Process Names
        Map<String, Total_Agility_Process_Configurations__mdt> configMap = new Map<String, Total_Agility_Process_Configurations__mdt>();
        for (Total_Agility_Process_Configurations__mdt config : TAJobResponseHelper.processConfigurations) {
            if(processNames.contains(config.Total_Agility_Process_Name__c)){
                configMap.put(config.Total_Agility_Process_Name__c, config);
            }
        }
        
        List<KTA_Job__c> ktaJobs = new List<KTA_Job__c>();
        // Iterate over all platform events
        for (JobResponse__e event : responses) {
            KTA_Job__c ktaJob = new KTA_Job__c(
                Inbound_Request_JSON__c = event.Response_Message__c,
            Process_Name__c = event.Process_Name__c,
            Request_Type__c ='Inbound'
                );
            try {
                // Get the configuration for the current event
                Total_Agility_Process_Configurations__mdt config = configMap.get(event.Process_Name__c);
                if (config == null) {
                    ktaJob.Exception__c = 'No configuration found for process name: ' + event.Process_Name__c;
                    continue;
                }
                
                // Check the Callback Execution Method
                String executionMethod = config.Callback_Execution_Method__c;
                String logicName = config.Callback_Logi_Apex_or_Flow_name__c;
                String logicNamespace = config.Callback_Logic_Namespace__c;                
                if (executionMethod == 'Apex') {
                    // Dynamically invoke the Apex class
                    Type callbackClassType = Type.forName(logicName);
                    if (callbackClassType != null) {
                        Object callbackInstance = callbackClassType.newInstance();
                        if (callbackInstance instanceof TACallbackProcessor) {
                            ((TACallbackProcessor) callbackInstance).execute(event.Response_Message__c);
                        } else {
                            ktaJob.Exception__c = 'Class does not implement TACallbackProcessor interface: ' + logicName;
                        }
                    } else {
                        ktaJob.Exception__c = 'Class not found: ' + logicName;
                    }
                } else if (executionMethod == 'Flow') {
                    // Call the Flow using Flow.Interview
                    Map<String, Object> flowInputs = new Map<String, Object>();
                    if(String.isNotBlank(config.Flow_Variable_mapping__c)){
                        flowInputs = FlowUtility.populateFlowVariables(config.Flow_Variable_mapping__c,event.Response_Message__c);
                    } else {
                        flowInputs.put('ResponseMessage', event.Response_Message__c);
                    }
                    if(!flowInputs.isEmpty()){
                        ktajob.Inbound_Request_Flow_Inputs__c = JSON.serialize(flowInputs);
                    }
                    if(!Test.isRunningTest()){
                        if(String.isNotBlank(logicNamespace)){
                            Flow.Interview flow = Flow.Interview.createInterview(logicNamespace, logicName, flowInputs);
                            flow.start();
                        }
                        else {
                            Flow.Interview flow = Flow.Interview.createInterview(logicName, flowInputs);
                            flow.start();
                        }
                        
                    }
                    
                } else {
                    ktaJob.Exception__c = 'Unknown execution method: ' + executionMethod;
                }
            } catch (Exception ex) {
                ktaJob.Exception__c = ex.getMessage();
            }
            ktaJobs.add(ktaJob);
        }
        if (!ktaJobs.isEmpty() && isLoggingEnabled) {
            Database.insert(ktaJobs, true, AccessLevel.SYSTEM_MODE);
        }
        
    }
}