ta-connector/main/default/objects/KTA_Job__c/KTA_Job__c.object-meta.xml
<CustomObject>
    <label>KTA Job</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>KTA Job</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KTA Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KTA_Job__c/fields/Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Id__c</fullName>
    <label>Document Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KTA_Job__c/fields/Request_Input_Variables__c.field-meta.xml
<CustomField>
    <fullName>Request_Input_Variables__c</fullName>
    <label>Request Input Variables</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ta-connector/main/default/objects/KTA_Job__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ta-connector/main/default/objects/KTA_Job__c/fields/TA_Response_Status__c.field-meta.xml
<CustomField>
    <fullName>TA_Response_Status__c</fullName>
    <label>TA Response Status</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TotalAgility_System_Configurations__c/TotalAgility_System_Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TotalAgility System Configurations</label>
</CustomObject>

ta-connector/main/default/objects/TotalAgility_System_Configurations__c/fields/Log_Cleanup_Cutoff_Days__c.field-meta.xml
<CustomField>
    <fullName>Log_Cleanup_Cutoff_Days__c</fullName>
    <label>Job Log Clean up Cutoff Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ta-connector/main/default/objects/TotalAgility_System_Configurations__c/fields/Log_Job_inbound_and_outbound_Requests__c.field-meta.xml
<CustomField>
    <fullName>Log_Job_inbound_and_outbound_Requests__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Log Job inbound and outbound  Requests</label>
    <type>Checkbox</type>
</CustomField>

ta-connector/main/default/objects/TotalAgility_System_Configurations__c/fields/Session_ID__c.field-meta.xml
<CustomField>
    <fullName>Session_ID__c</fullName>
    <label>Session ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ta-connector/main/default/objects/TotalAgility_System_Configurations__c/fields/Total_Agility_End_point_URL__c.field-meta.xml
<CustomField>
    <fullName>Total_Agility_End_point_URL__c</fullName>
    <label>Total Agility End point URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ta-connector/main/default/classes/TACreateJobWithDocRequestInvocableTest.cls
/*
 * Test class for TACreateJobWithDocRequestInvocable
 */
@IsTest
private class TACreateJobWithDocRequestInvocableTest {

    @TestSetup
    static void setup() {
        // Create test data needed for the tests
        // Example: Insert required records
        Account acc = new Account(Name = 'Test Account');
        insert acc;

        Contact con = new Contact(FirstName = 'Test', LastName = 'Contact', AccountId = acc.Id);
        insert con;
        // Create test data for ContentVersion document
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Test Document',
            PathOnClient = 'TestDocument.pdf',
            VersionData = Blob.valueOf('Test content'),
            IsMajorVersion = true
        );
        insert contentVersion;

            // Create an org-level instance of the custom setting
        TotalAgility_System_Configurations__c orgLevelSetting = 
        new TotalAgility_System_Configurations__c(
            // Set field values
            Log_Cleanup_Cutoff_Days__c = 30,
            Log_Job_inbound_and_outbound_Requests__c = true,
            Session_ID__c = 'TestSession12345',
            Total_Agility_End_point_URL__c = 'https://example.com/endpoint'
        );

    // Insert the custom setting
    insert orgLevelSetting;

        // Add any other records required for the tests
    }

    @IsTest
    static void testSuccessResponse() {
        
        

        // Query for the document ID created in the test setup method
        ContentVersion contentVersion = [SELECT Id, FileExtension, ContentDocumentId FROM ContentVersion WHERE Title = 'Test Document' LIMIT 1];
        System.assertEquals('pdf', contentVersion.FileExtension);

        // Create an instance of the RequestWrapper and set its fields
        TACreateJobWithDocRequestInvocable.RequestWrapper requestWrapper = new TACreateJobWithDocRequestInvocable.RequestWrapper();
        requestWrapper.processName = 'Test Process';
        requestWrapper.documentIds = new List<String>{contentVersion.Id};
        requestWrapper.inputs = new List<InputVariables>();
        InputVariables input1 = new InputVariables();
        input1.Id = 'Input1';
        input1.Value = 'Value1';

        InputVariables input2 = new InputVariables();
        input2.Id = 'Input2';
        input2.Value = 'Value2';

        requestWrapper.inputs.add(input1);
        requestWrapper.inputs.add(input2);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TotalAgilityMockCallout());
        List<TACreateJobWithDocRequestInvocable.RequestWrapper> requests = new List<TACreateJobWithDocRequestInvocable.RequestWrapper>{requestWrapper};

        List<TAResponseWrapper> responses =  TACreateJobWithDocRequestInvocable.processRequests(requests);
        Test.stopTest();
        KTA_Job__c job = [SELECT Id,Document_Id__c, Name,Request_Input_Variables__c, Request_Type__c FROM KTA_Job__c WHERE Request_Type__c = 'Outbound' LIMIT 1];
        System.assertNotEquals(null, job, 'Job should have been created');
        System.assert(job.Request_Input_Variables__c.contains('Input1'));
        System.assert(job.Document_Id__c.contains(contentVersion.Id));
        System.assertEquals('D6D41193CA1D11EFA852B85C5C297990', responses[0].jobID, 'Job ID should not be null');

    }
    @IsTest
    static void testFailureResponse() {
        
        

        // Query for the document ID created in the test setup method
        ContentVersion contentVersion = [SELECT Id, FileExtension, ContentDocumentId FROM ContentVersion WHERE Title = 'Test Document' LIMIT 1];
        System.assertEquals('pdf', contentVersion.FileExtension);

        // Create an instance of the RequestWrapper and set its fields
        TACreateJobWithDocRequestInvocable.RequestWrapper requestWrapper = new TACreateJobWithDocRequestInvocable.RequestWrapper();
        requestWrapper.processName = 'Test Process';
        requestWrapper.documentIds = new List<String>{contentVersion.Id};
        requestWrapper.inputs = new List<InputVariables>();
        InputVariables input1 = new InputVariables();
        input1.Id = 'Input1';
        input1.Value = 'Value1';

        InputVariables input2 = new InputVariables();
        input2.Id = 'Input2';
        input2.Value = 'Value2';

        requestWrapper.inputs.add(input1);
        requestWrapper.inputs.add(input2);
        Test.startTest();
        TotalAgilityMockCallout mockObj = new TotalAgilityMockCallout();
        mockObj.responseBody = '{"error":"Invalid request"}';
        mockObj.responseStatus = 'Bad Request';
        mockObj.responseStatusCode = 400;

        Test.setMock(HttpCalloutMock.class, mockObj);
        List<TACreateJobWithDocRequestInvocable.RequestWrapper> requests = new List<TACreateJobWithDocRequestInvocable.RequestWrapper>{requestWrapper};

        List<TAResponseWrapper> responses =  TACreateJobWithDocRequestInvocable.processRequests(requests);
        Test.stopTest();
        KTA_Job__c job = [SELECT Id,Document_Id__c, Name,Request_Input_Variables__c, Request_Type__c, TA_Response_Status__c FROM KTA_Job__c WHERE Request_Type__c = 'Outbound' LIMIT 1];
        System.debug(job.TA_Response_Status__c);
        System.Assert(job.TA_Response_Status__c.contains('Bad Request'));        
        System.Assert(responses[0].resultMessage.contains('Failure response from TotalAgility'), 'Expecting Failure response');

    }
    @IsTest
    static void testUnexpectedResponse() {
        
        

        // Query for the document ID created in the test setup method
        ContentVersion contentVersion = [SELECT Id, FileExtension, ContentDocumentId FROM ContentVersion WHERE Title = 'Test Document' LIMIT 1];
        System.assertEquals('pdf', contentVersion.FileExtension);

        // Create an instance of the RequestWrapper and set its fields
        TACreateJobWithDocRequestInvocable.RequestWrapper requestWrapper = new TACreateJobWithDocRequestInvocable.RequestWrapper();
        requestWrapper.processName = 'Test Process';
        requestWrapper.documentIds = new List<String>{contentVersion.Id};
        requestWrapper.inputs = new List<InputVariables>();
        InputVariables input1 = new InputVariables();
        input1.Id = 'Input1';
        input1.Value = 'Value1';

        InputVariables input2 = new InputVariables();
        input2.Id = 'Input2';
        input2.Value = 'Value2';

        requestWrapper.inputs.add(input1);
        requestWrapper.inputs.add(input2);
        Test.startTest();
        TotalAgilityMockCallout mockObj = new TotalAgilityMockCallout();
        mockObj.responseBody = '{"error":"Invalid request"}';
        mockObj.responseStatus = 'Bad response';
        mockObj.responseStatusCode = 200;

        Test.setMock(HttpCalloutMock.class, mockObj);
        List<TACreateJobWithDocRequestInvocable.RequestWrapper> requests = new List<TACreateJobWithDocRequestInvocable.RequestWrapper>{requestWrapper};

        List<TAResponseWrapper> responses =  TACreateJobWithDocRequestInvocable.processRequests(requests);
        Test.stopTest();
        KTA_Job__c job = [SELECT Id,Document_Id__c, Name,Request_Input_Variables__c, Request_Type__c, TA_Response_Status__c FROM KTA_Job__c WHERE Request_Type__c = 'Outbound' LIMIT 1];
        System.debug(job.TA_Response_Status__c);
        System.Assert(job.TA_Response_Status__c.contains('Bad response'));        
        System.Assert(responses[0].resultMessage.contains('Unexpected response from TotalAgility'), 'Expecting Unexpected response');

    }
}